#Paty projekt do predmetu ITY 2013/2014
#Autor: Lukas Pelanek
#datum: 5. kvetna 2014

soubor=proj5

proj5: proj5.tex
	latex $(soubor).tex
	latex $(soubor).tex
	dvips $(soubor).dvi
	ps2pdf $(soubor).ps
