#Soubor: makefile
#Datum: 2014/05/04
#Autor: Lukas Pelanek, xpelan03@fit.vutbr.cz
#Projekt: Synchronizace procesu, projekt c. 2 pro predmet IOS

NAME=proj2

proj2:
	gcc -std=gnu99 -Wall -Wextra -Werror -pedantic $(NAME).c -o rivercrossing -lrt -lpthread
