# Soubor:  Makefile
# Datum:   2017/4/29
# Autor:   Bc. Lukas Pelanek, xpelan03@stud.fit.vutbr.cz
# Projekt: KKO, Huffmanovo adaptivni kodovani

CC =g++
CFLAGS =-pedantic -Wextra -std=c++11
FILES =main.cpp ahed.cpp
PROGRAM =ahed

all:
	$(CC) $(CFLAGS) $(FILES) -o $(PROGRAM)

clean:
	rm $(PROGRAM)

