# Soubor:	Makefile
# Datum:	2017/03/06
# Autor:	Bc. Lukas Pelanek, xpelan03@stud.fit.vutbr.cz
# Projekt:	FLP, rka-2-dka
# Popis:	Prevod rozsireneho konecneho automatu na deterministicky konecny automat

all:
	ghc xpelan03.hs -o rka-2-dka

clean:
	rm rka-2-dka *.o *.hi