#
# Projekt: Typografie a publikování  3. projekt
# Autor:   Lukáš Pelánek
# Datum:   6. 4. 2014
#

name=proj3


proj: proj3.tex
	latex $(name).tex
	latex $(name).tex
	dvips $(name).dvi
	ps2pdf $(name).ps
