#
# Projekt: Typografie a publikování  2. projekt
# Autor:   Lukáš Pelánek
# Datum:   27. 3. 2014
#

name=proj2


proj: proj2.tex
	latex $(name).tex
	latex $(name).tex
	dvips -t a4 $(name).dvi
	ps2pdf $(name).ps
