# Soubor:  Makefile
# Datum:   2017/10/17
# Autor:   Bc. Lukas Pelanek, xpelan03@stud.fit.vutbr.cz
# Projekt: BMS, projekt 1

CC =g++
CFLAGS =-pedantic -Wextra -std=c++11
FILES =Main.cpp
PROGRAM =p1

all:
	$(CC) $(CFLAGS) $(FILES) -o $(PROGRAM)

clean:
	rm $(PROGRAM)